# to make vim colorscheme works under tmux
export TERM=xterm-256color

# set the editor for Git and also other programs
export VISUAL=vim
export EDITOR="$VISUAL"

# for Git
git config --global user.name "<put-your-name-here>"
git config --global user.email "<put-your-email-here>"
git config --global color.ui true
